name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  repository:
    description: 'get the latest version of the repository'
    required: true
    default: '0.0.1'
outputs:
  next_version:
    description: 'The next version of the repository'
runs:
  using: 'node16'
  main: 'dist/index.js'
