name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  repository:
    description: 'get the latest version of the repository'
    required: true
    default: '0.0.1'
outputs:
  data:
    description: 'The data from docker hub'
runs:
  using: 'node16'
  main: 'dist/index.js'
